USE wynajem_db
GO

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Wynajem_Konto_Login')
BEGIN
    ALTER TABLE [wynajem] DROP CONSTRAINT FK__Wynajem_Konto_Login
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Wynajem_Bot_ID')
BEGIN
    ALTER TABLE [wynajem] DROP CONSTRAINT FK__Wynajem_Bot_ID
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Bot_Srodowisko_Nazwa_Gry')
BEGIN
    ALTER TABLE [bot] DROP CONSTRAINT FK__Bot_Srodowisko_Nazwa_Gry
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Bot_Mecz_ID')
BEGIN
    ALTER TABLE [bot] DROP CONSTRAINT FK__Bot_Mecz_ID
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Mecz_Bot1_ID')
BEGIN
    ALTER TABLE [mecz] DROP CONSTRAINT FK__Mecz_Bot1_ID
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Mecz_Bot2_ID')
BEGIN
    ALTER TABLE [mecz] DROP CONSTRAINT FK__Mecz_Bot2_ID
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Mecz_Srodowisko_Nazwa_Gry')
BEGIN
    ALTER TABLE [mecz] DROP CONSTRAINT FK__Mecz_Srodowisko_Nazwa_Gry
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Osiagniecie_Konto_Login')
BEGIN
    ALTER TABLE [osiagniecie] DROP CONSTRAINT FK__Osiagniecie_Konto_Login
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Osiagniecie_Bot_ID')
BEGIN
    ALTER TABLE [osiagniecie] DROP CONSTRAINT FK__Osiagniecie_Bot_ID
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Osiagniecie_Przedmiot_ID')
BEGIN
    ALTER TABLE [osiagniecie] DROP CONSTRAINT FK__Osiagniecie_Przedmiot_ID
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Doladowanie_Konto_Login')
BEGIN
    ALTER TABLE [doladowanie] DROP CONSTRAINT FK__Doladowanie_Konto_Login
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Recenzja_Konto_Login')
BEGIN
    ALTER TABLE [recenzja] DROP CONSTRAINT FK__Recenzja_Konto_Login
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Recenzja_Bot_ID')
BEGIN
    ALTER TABLE [recenzja] DROP CONSTRAINT FK__Recenzja_Bot_ID
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Wiadomosc_Nadawca')
BEGIN
    ALTER TABLE [wiadomosc] DROP CONSTRAINT FK__Wiadomosc_Nadawca
END

IF EXISTS (SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK__Wiadomosc_Odbiorca')
BEGIN
    ALTER TABLE [wiadomosc] DROP CONSTRAINT FK__Wiadomosc_Odbiorca
END