USE wynajem_db
GO

DROP TABLE IF EXISTS [wynajem]
DROP TABLE IF EXISTS [bot]
DROP TABLE IF EXISTS [srodowisko]
DROP TABLE IF EXISTS [mecz]
DROP TABLE IF EXISTS [przedmiot]
DROP TABLE IF EXISTS [osiagniecie]
DROP TABLE IF EXISTS [doladowanie]
DROP TABLE IF EXISTS [recenzja]
DROP TABLE IF EXISTS [wiadomosc]
DROP TABLE IF EXISTS [konto]
